version: "3.7"

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/usr/src/app
#    env_file:
#      - .env
    depends_on:
      - redis
    restart: on-failure
    environment:
      - PORT=3000
      - NODE_ENV=development
      - ENV_NAME=local
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    # Run a command against the development stage of the image
    ports:
      - "3000:3000"

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
